// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace RestSys.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Login - Use 'LoginParams' to pass parameters into this method.
        /// </summary>
        public void Login()
        {
            #region Variable Declarations
            HtmlHyperlink uISkladHyperlink = this.UIRestSysHomePageInterWindow.UIRestSysHomePageDocument.UIMenuCustom.UISkladHyperlink;
            HtmlEdit uIUsernameEdit = this.UIRestSysHomePageInterWindow.UIRestSysLoginDocument.UIUsernameEdit;
            HtmlEdit uIPasswordEdit = this.UIRestSysHomePageInterWindow.UIRestSysLoginDocument.UIPasswordEdit;
            #endregion

            // Click 'Sklad' link
            Mouse.Click(uISkladHyperlink, new Point(28, 30));

            // Type 'uxsoft' in 'Username:' text box
            uIUsernameEdit.Text = this.LoginParams.UIUsernameEditText;

            // Type '********' in 'Password:' text box
            uIPasswordEdit.Password = this.LoginParams.UIPasswordEditPassword;

            // Type '{Enter}' in 'Password:' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginParams.UIPasswordEditSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual LoginParams LoginParams
        {
            get
            {
                if ((this.mLoginParams == null))
                {
                    this.mLoginParams = new LoginParams();
                }
                return this.mLoginParams;
            }
        }
        
        public UIRestSysHomePageInterWindow UIRestSysHomePageInterWindow
        {
            get
            {
                if ((this.mUIRestSysHomePageInterWindow == null))
                {
                    this.mUIRestSysHomePageInterWindow = new UIRestSysHomePageInterWindow();
                }
                return this.mUIRestSysHomePageInterWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginParams mLoginParams;
        
        private UIRestSysHomePageInterWindow mUIRestSysHomePageInterWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Login'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class LoginParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'uxsoft' in 'Username:' text box
        /// </summary>
        public string UIUsernameEditText = "uxsoft";
        
        /// <summary>
        /// Type '********' in 'Password:' text box
        /// </summary>
        public string UIPasswordEditPassword = "Ee5ENuo12F6KwofRP+EDulOoX/toicSsp8kPJVuZVq8mIBiHsfaiIg==";
        
        /// <summary>
        /// Type '{Enter}' in 'Password:' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRestSysHomePageInterWindow : BrowserWindow
    {
        
        public UIRestSysHomePageInterWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "RestSys Home Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("RestSys Home Page");
            this.WindowTitles.Add("RestSys Login");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIRestSysHomePageDocument UIRestSysHomePageDocument
        {
            get
            {
                if ((this.mUIRestSysHomePageDocument == null))
                {
                    this.mUIRestSysHomePageDocument = new UIRestSysHomePageDocument(this);
                }
                return this.mUIRestSysHomePageDocument;
            }
        }
        
        public UIRestSysLoginDocument UIRestSysLoginDocument
        {
            get
            {
                if ((this.mUIRestSysLoginDocument == null))
                {
                    this.mUIRestSysLoginDocument = new UIRestSysLoginDocument(this);
                }
                return this.mUIRestSysLoginDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIRestSysHomePageDocument mUIRestSysHomePageDocument;
        
        private UIRestSysLoginDocument mUIRestSysLoginDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRestSysHomePageDocument : HtmlDocument
    {
        
        public UIRestSysHomePageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "RestSys Home Page";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56345/";
            this.WindowTitles.Add("RestSys Home Page");
            #endregion
        }
        
        #region Properties
        public UIMenuCustom UIMenuCustom
        {
            get
            {
                if ((this.mUIMenuCustom == null))
                {
                    this.mUIMenuCustom = new UIMenuCustom(this);
                }
                return this.mUIMenuCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuCustom mUIMenuCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIMenuCustom : HtmlCustom
    {
        
        public UIMenuCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "UL";
            this.SearchProperties["Id"] = "menu";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"menu\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("RestSys Home Page");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISkladHyperlink
        {
            get
            {
                if ((this.mUISkladHyperlink == null))
                {
                    this.mUISkladHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISkladHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISkladHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISkladHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISkladHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sklad";
                    this.mUISkladHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Stocks";
                    this.mUISkladHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISkladHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:56345/Stocks";
                    this.mUISkladHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISkladHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Stocks\"";
                    this.mUISkladHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUISkladHyperlink.WindowTitles.Add("RestSys Home Page");
                    #endregion
                }
                return this.mUISkladHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISkladHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIRestSysLoginDocument : HtmlDocument
    {
        
        public UIRestSysLoginDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "RestSys Login";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:56345/Account/Login?ReturnUrl=%2fStocks";
            this.WindowTitles.Add("RestSys Login");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "username";
                    this.mUIUsernameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "username";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Username:";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"username\" id=\"username\" type=\"text";
                    this.mUIUsernameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUsernameEdit.WindowTitles.Add("RestSys Login");
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password:";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"password\" id=\"password\" type=\"pass";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("RestSys Login");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUsernameEdit;
        
        private HtmlEdit mUIPasswordEdit;
        #endregion
    }
}
