//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 9. 5. 2014 0:57:40
namespace RestSys.Client.Services.EntityService
{
    
    /// <summary>
    /// There are no comments for RSDbContext in the schema.
    /// </summary>
    public partial class RSDbContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new RSDbContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSDbContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "RestSys.Models", "RestSys.Client.Services.EntityService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("RestSys.Client.Services.EntityService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RestSys.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Navigation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSNavigationItem> Navigation
        {
            get
            {
                if ((this._Navigation == null))
                {
                    this._Navigation = base.CreateQuery<RSNavigationItem>("Navigation");
                }
                return this._Navigation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSNavigationItem> _Navigation;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSProduct> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<RSProduct>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSProduct> _Products;
        /// <summary>
        /// There are no comments for OrderItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSOrderItem> OrderItems
        {
            get
            {
                if ((this._OrderItems == null))
                {
                    this._OrderItems = base.CreateQuery<RSOrderItem>("OrderItems");
                }
                return this._OrderItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSOrderItem> _OrderItems;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSOrder> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<RSOrder>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSOrder> _Orders;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSUser> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<RSUser>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSUser> _Users;
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSReceipt> Receipts
        {
            get
            {
                if ((this._Receipts == null))
                {
                    this._Receipts = base.CreateQuery<RSReceipt>("Receipts");
                }
                return this._Receipts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSReceipt> _Receipts;
        /// <summary>
        /// There are no comments for StockItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSStockItem> StockItems
        {
            get
            {
                if ((this._StockItems == null))
                {
                    this._StockItems = base.CreateQuery<RSStockItem>("StockItems");
                }
                return this._StockItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSStockItem> _StockItems;
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSStock> Stocks
        {
            get
            {
                if ((this._Stocks == null))
                {
                    this._Stocks = base.CreateQuery<RSStock>("Stocks");
                }
                return this._Stocks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSStock> _Stocks;
        /// <summary>
        /// There are no comments for Styles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSStyle> Styles
        {
            get
            {
                if ((this._Styles == null))
                {
                    this._Styles = base.CreateQuery<RSStyle>("Styles");
                }
                return this._Styles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSStyle> _Styles;
        /// <summary>
        /// There are no comments for Navigation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNavigation(RSNavigationItem rSNavigationItem)
        {
            base.AddObject("Navigation", rSNavigationItem);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(RSProduct rSProduct)
        {
            base.AddObject("Products", rSProduct);
        }
        /// <summary>
        /// There are no comments for OrderItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrderItems(RSOrderItem rSOrderItem)
        {
            base.AddObject("OrderItems", rSOrderItem);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrders(RSOrder rSOrder)
        {
            base.AddObject("Orders", rSOrder);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(RSUser rSUser)
        {
            base.AddObject("Users", rSUser);
        }
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToReceipts(RSReceipt rSReceipt)
        {
            base.AddObject("Receipts", rSReceipt);
        }
        /// <summary>
        /// There are no comments for StockItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStockItems(RSStockItem rSStockItem)
        {
            base.AddObject("StockItems", rSStockItem);
        }
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStocks(RSStock rSStock)
        {
            base.AddObject("Stocks", rSStock);
        }
        /// <summary>
        /// There are no comments for Styles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStyles(RSStyle rSStyle)
        {
            base.AddObject("Styles", rSStyle);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"RestSys.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\">" +
                "<EntityType Name=\"RSNavigationItem\"><Key><PropertyRef Name=\"Id\" /></Key><Propert" +
                "y Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ChildrenOrder\" T" +
                "ype=\"Edm.String\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Property Name=\"De" +
                "scription\" Type=\"Edm.String\" /><Property Name=\"Image\" Type=\"Edm.String\" /><Prope" +
                "rty Name=\"IsRoot\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Color\" T" +
                "ype=\"Edm.String\" /><NavigationProperty Name=\"Children\" Relationship=\"RestSys.Mod" +
                "els.RSNavigationItem_Children_RSNavigationItem_Parent\" ToRole=\"RSNavigationItem_" +
                "Parent\" FromRole=\"RSNavigationItem_Children\" /><NavigationProperty Name=\"Parent\"" +
                " Relationship=\"RestSys.Models.RSNavigationItem_Children_RSNavigationItem_Parent\"" +
                " ToRole=\"RSNavigationItem_Children\" FromRole=\"RSNavigationItem_Parent\" /><Naviga" +
                "tionProperty Name=\"ProductLink\" Relationship=\"RestSys.Models.RSNavigationItem_Pr" +
                "oductLink_RSProduct_DependentNavigationItems\" ToRole=\"RSProduct_DependentNavigat" +
                "ionItems\" FromRole=\"RSNavigationItem_ProductLink\" /></EntityType><EntityType Nam" +
                "e=\"RSProduct\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm." +
                "Int32\" Nullable=\"false\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Property N" +
                "ame=\"Description\" Type=\"Edm.String\" /><Property Name=\"Price\" Type=\"Edm.Double\" N" +
                "ullable=\"false\" /><Property Name=\"ShowOnMenu\" Type=\"Edm.Boolean\" Nullable=\"false" +
                "\" /><Property Name=\"SerialNumber\" Type=\"Edm.String\" /><Property Name=\"Category\" " +
                "Type=\"Edm.String\" /><NavigationProperty Name=\"DependentNavigationItems\" Relation" +
                "ship=\"RestSys.Models.RSNavigationItem_ProductLink_RSProduct_DependentNavigationI" +
                "tems\" ToRole=\"RSNavigationItem_ProductLink\" FromRole=\"RSProduct_DependentNavigat" +
                "ionItems\" /><NavigationProperty Name=\"DependentOrderItems\" Relationship=\"RestSys" +
                ".Models.RSProduct_DependentOrderItems_RSOrderItem_Product\" ToRole=\"RSOrderItem_P" +
                "roduct\" FromRole=\"RSProduct_DependentOrderItems\" /><NavigationProperty Name=\"Sto" +
                "cks\" Relationship=\"RestSys.Models.RSProduct_Stocks_RSStockItem_Product\" ToRole=\"" +
                "RSStockItem_Product\" FromRole=\"RSProduct_Stocks\" /></EntityType><EntityType Name" +
                "=\"RSOrderItem\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm" +
                ".Int32\" Nullable=\"false\" /><Property Name=\"CreatedOn\" Type=\"Edm.DateTime\" Nullab" +
                "le=\"false\" /><Property Name=\"State\" Type=\"Edm.Int32\" Nullable=\"false\" /><Navigat" +
                "ionProperty Name=\"Order\" Relationship=\"RestSys.Models.RSOrderItem_Order_RSOrder_" +
                "Items\" ToRole=\"RSOrder_Items\" FromRole=\"RSOrderItem_Order\" /><NavigationProperty" +
                " Name=\"Product\" Relationship=\"RestSys.Models.RSProduct_DependentOrderItems_RSOrd" +
                "erItem_Product\" ToRole=\"RSProduct_DependentOrderItems\" FromRole=\"RSOrderItem_Pro" +
                "duct\" /><NavigationProperty Name=\"Receipt\" Relationship=\"RestSys.Models.RSOrderI" +
                "tem_Receipt_RSReceipt_PaidItems\" ToRole=\"RSReceipt_PaidItems\" FromRole=\"RSOrderI" +
                "tem_Receipt\" /></EntityType><EntityType Name=\"RSOrder\"><Key><PropertyRef Name=\"I" +
                "d\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Nam" +
                "e=\"Title\" Type=\"Edm.String\" /><Property Name=\"CreatedOn\" Type=\"Edm.DateTime\" Nul" +
                "lable=\"false\" /><Property Name=\"Active\" Type=\"Edm.Boolean\" Nullable=\"false\" /><P" +
                "roperty Name=\"Notes\" Type=\"Edm.String\" /><NavigationProperty Name=\"Attendees\" Re" +
                "lationship=\"RestSys.Models.RSOrder_Attendees_RSUser_AttendedOrders\" ToRole=\"RSUs" +
                "er_AttendedOrders\" FromRole=\"RSOrder_Attendees\" /><NavigationProperty Name=\"Item" +
                "s\" Relationship=\"RestSys.Models.RSOrderItem_Order_RSOrder_Items\" ToRole=\"RSOrder" +
                "Item_Order\" FromRole=\"RSOrder_Items\" /><NavigationProperty Name=\"Receipts\" Relat" +
                "ionship=\"RestSys.Models.RSOrder_Receipts_RSReceipt_Order\" ToRole=\"RSReceipt_Orde" +
                "r\" FromRole=\"RSOrder_Receipts\" /></EntityType><EntityType Name=\"RSUser\"><Key><Pr" +
                "opertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false" +
                "\" /><Property Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Username\" Type=\"Ed" +
                "m.String\" /><Property Name=\"PasswordHash\" Type=\"Edm.Binary\" /><Property Name=\"Pa" +
                "sswordSalt\" Type=\"Edm.Binary\" /><Property Name=\"IsAdmin\" Type=\"Edm.Boolean\" Null" +
                "able=\"false\" /><Property Name=\"IsWaiter\" Type=\"Edm.Boolean\" Nullable=\"false\" /><" +
                "NavigationProperty Name=\"AttendedOrders\" Relationship=\"RestSys.Models.RSOrder_At" +
                "tendees_RSUser_AttendedOrders\" ToRole=\"RSOrder_Attendees\" FromRole=\"RSUser_Atten" +
                "dedOrders\" /><NavigationProperty Name=\"Receipts\" Relationship=\"RestSys.Models.RS" +
                "User_Receipts_RSReceipt_User\" ToRole=\"RSReceipt_User\" FromRole=\"RSUser_Receipts\"" +
                " /></EntityType><EntityType Name=\"RSReceipt\"><Key><PropertyRef Name=\"Id\" /></Key" +
                "><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Created" +
                "On\" Type=\"Edm.DateTime\" Nullable=\"false\" /><NavigationProperty Name=\"Order\" Rela" +
                "tionship=\"RestSys.Models.RSOrder_Receipts_RSReceipt_Order\" ToRole=\"RSOrder_Recei" +
                "pts\" FromRole=\"RSReceipt_Order\" /><NavigationProperty Name=\"PaidItems\" Relations" +
                "hip=\"RestSys.Models.RSOrderItem_Receipt_RSReceipt_PaidItems\" ToRole=\"RSOrderItem" +
                "_Receipt\" FromRole=\"RSReceipt_PaidItems\" /><NavigationProperty Name=\"User\" Relat" +
                "ionship=\"RestSys.Models.RSUser_Receipts_RSReceipt_User\" ToRole=\"RSUser_Receipts\"" +
                " FromRole=\"RSReceipt_User\" /></EntityType><EntityType Name=\"RSStockItem\"><Key><P" +
                "ropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fals" +
                "e\" /><Property Name=\"Amount\" Type=\"Edm.Double\" Nullable=\"false\" /><NavigationPro" +
                "perty Name=\"Product\" Relationship=\"RestSys.Models.RSProduct_Stocks_RSStockItem_P" +
                "roduct\" ToRole=\"RSProduct_Stocks\" FromRole=\"RSStockItem_Product\" /><NavigationPr" +
                "operty Name=\"Stock\" Relationship=\"RestSys.Models.RSStockItem_Stock_RSStock_Items" +
                "\" ToRole=\"RSStock_Items\" FromRole=\"RSStockItem_Stock\" /></EntityType><EntityType" +
                " Name=\"RSStock\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Property" +
                " Name=\"Unit\" Type=\"Edm.String\" /><Property Name=\"Notes\" Type=\"Edm.String\" /><Pro" +
                "perty Name=\"SerialNumber\" Type=\"Edm.String\" /><NavigationProperty Name=\"Items\" R" +
                "elationship=\"RestSys.Models.RSStockItem_Stock_RSStock_Items\" ToRole=\"RSStockItem" +
                "_Stock\" FromRole=\"RSStock_Items\" /></EntityType><EntityType Name=\"RSStyle\"><Key>" +
                "<PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fa" +
                "lse\" /><Property Name=\"Code\" Type=\"Edm.String\" /><Property Name=\"Path\" Type=\"Edm" +
                ".String\" /><Property Name=\"Type\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property N" +
                "ame=\"Title\" Type=\"Edm.String\" /><Property Name=\"Notes\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"Selected\" Type=\"Edm.Boolean\" Nullable=\"false\" /></EntityType><Associa" +
                "tion Name=\"RSNavigationItem_Children_RSNavigationItem_Parent\"><End Type=\"RestSys" +
                ".Models.RSNavigationItem\" Role=\"RSNavigationItem_Parent\" Multiplicity=\"*\" /><End" +
                " Type=\"RestSys.Models.RSNavigationItem\" Role=\"RSNavigationItem_Children\" Multipl" +
                "icity=\"0..1\" /></Association><Association Name=\"RSNavigationItem_ProductLink_RSP" +
                "roduct_DependentNavigationItems\"><End Type=\"RestSys.Models.RSProduct\" Role=\"RSPr" +
                "oduct_DependentNavigationItems\" Multiplicity=\"0..1\" /><End Type=\"RestSys.Models." +
                "RSNavigationItem\" Role=\"RSNavigationItem_ProductLink\" Multiplicity=\"*\" /></Assoc" +
                "iation><Association Name=\"RSProduct_DependentOrderItems_RSOrderItem_Product\"><En" +
                "d Type=\"RestSys.Models.RSOrderItem\" Role=\"RSOrderItem_Produ";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "ct\" Multiplicity=\"*\" /><End Type=\"RestSys.Models.RSProduct\" Role=\"RSProduct_Depen" +
                "dentOrderItems\" Multiplicity=\"0..1\" /></Association><Association Name=\"RSProduct" +
                "_Stocks_RSStockItem_Product\"><End Type=\"RestSys.Models.RSStockItem\" Role=\"RSStoc" +
                "kItem_Product\" Multiplicity=\"*\" /><End Type=\"RestSys.Models.RSProduct\" Role=\"RSP" +
                "roduct_Stocks\" Multiplicity=\"0..1\" /></Association><Association Name=\"RSOrderIte" +
                "m_Order_RSOrder_Items\"><End Type=\"RestSys.Models.RSOrder\" Role=\"RSOrder_Items\" M" +
                "ultiplicity=\"0..1\" /><End Type=\"RestSys.Models.RSOrderItem\" Role=\"RSOrderItem_Or" +
                "der\" Multiplicity=\"*\" /></Association><Association Name=\"RSOrderItem_Receipt_RSR" +
                "eceipt_PaidItems\"><End Type=\"RestSys.Models.RSReceipt\" Role=\"RSReceipt_PaidItems" +
                "\" Multiplicity=\"0..1\" /><End Type=\"RestSys.Models.RSOrderItem\" Role=\"RSOrderItem" +
                "_Receipt\" Multiplicity=\"*\" /></Association><Association Name=\"RSOrder_Attendees_" +
                "RSUser_AttendedOrders\"><End Type=\"RestSys.Models.RSUser\" Role=\"RSUser_AttendedOr" +
                "ders\" Multiplicity=\"*\" /><End Type=\"RestSys.Models.RSOrder\" Role=\"RSOrder_Attend" +
                "ees\" Multiplicity=\"*\" /></Association><Association Name=\"RSOrder_Receipts_RSRece" +
                "ipt_Order\"><End Type=\"RestSys.Models.RSReceipt\" Role=\"RSReceipt_Order\" Multiplic" +
                "ity=\"*\" /><End Type=\"RestSys.Models.RSOrder\" Role=\"RSOrder_Receipts\" Multiplicit" +
                "y=\"0..1\" /></Association><Association Name=\"RSUser_Receipts_RSReceipt_User\"><End" +
                " Type=\"RestSys.Models.RSReceipt\" Role=\"RSReceipt_User\" Multiplicity=\"*\" /><End T" +
                "ype=\"RestSys.Models.RSUser\" Role=\"RSUser_Receipts\" Multiplicity=\"0..1\" /></Assoc" +
                "iation><Association Name=\"RSStockItem_Stock_RSStock_Items\"><End Type=\"RestSys.Mo" +
                "dels.RSStock\" Role=\"RSStock_Items\" Multiplicity=\"0..1\" /><End Type=\"RestSys.Mode" +
                "ls.RSStockItem\" Role=\"RSStockItem_Stock\" Multiplicity=\"*\" /></Association><Entit" +
                "yContainer Name=\"RSDbContext\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=" +
                "\"Navigation\" EntityType=\"RestSys.Models.RSNavigationItem\" /><EntitySet Name=\"Pro" +
                "ducts\" EntityType=\"RestSys.Models.RSProduct\" /><EntitySet Name=\"OrderItems\" Enti" +
                "tyType=\"RestSys.Models.RSOrderItem\" /><EntitySet Name=\"Orders\" EntityType=\"RestS" +
                "ys.Models.RSOrder\" /><EntitySet Name=\"Users\" EntityType=\"RestSys.Models.RSUser\" " +
                "/><EntitySet Name=\"Receipts\" EntityType=\"RestSys.Models.RSReceipt\" /><EntitySet " +
                "Name=\"StockItems\" EntityType=\"RestSys.Models.RSStockItem\" /><EntitySet Name=\"Sto" +
                "cks\" EntityType=\"RestSys.Models.RSStock\" /><EntitySet Name=\"Styles\" EntityType=\"" +
                "RestSys.Models.RSStyle\" /><AssociationSet Name=\"RSNavigationItem_Children\" Assoc" +
                "iation=\"RestSys.Models.RSNavigationItem_Children_RSNavigationItem_Parent\"><End R" +
                "ole=\"RSNavigationItem_Children\" EntitySet=\"Navigation\" /><End Role=\"RSNavigation" +
                "Item_Parent\" EntitySet=\"Navigation\" /></AssociationSet><AssociationSet Name=\"RSP" +
                "roduct_DependentNavigationItems\" Association=\"RestSys.Models.RSNavigationItem_Pr" +
                "oductLink_RSProduct_DependentNavigationItems\"><End Role=\"RSNavigationItem_Produc" +
                "tLink\" EntitySet=\"Navigation\" /><End Role=\"RSProduct_DependentNavigationItems\" E" +
                "ntitySet=\"Products\" /></AssociationSet><AssociationSet Name=\"RSOrderItem_Product" +
                "\" Association=\"RestSys.Models.RSProduct_DependentOrderItems_RSOrderItem_Product\"" +
                "><End Role=\"RSProduct_DependentOrderItems\" EntitySet=\"Products\" /><End Role=\"RSO" +
                "rderItem_Product\" EntitySet=\"OrderItems\" /></AssociationSet><AssociationSet Name" +
                "=\"RSStockItem_Product\" Association=\"RestSys.Models.RSProduct_Stocks_RSStockItem_" +
                "Product\"><End Role=\"RSProduct_Stocks\" EntitySet=\"Products\" /><End Role=\"RSStockI" +
                "tem_Product\" EntitySet=\"StockItems\" /></AssociationSet><AssociationSet Name=\"RSO" +
                "rder_Items\" Association=\"RestSys.Models.RSOrderItem_Order_RSOrder_Items\"><End Ro" +
                "le=\"RSOrderItem_Order\" EntitySet=\"OrderItems\" /><End Role=\"RSOrder_Items\" Entity" +
                "Set=\"Orders\" /></AssociationSet><AssociationSet Name=\"RSReceipt_PaidItems\" Assoc" +
                "iation=\"RestSys.Models.RSOrderItem_Receipt_RSReceipt_PaidItems\"><End Role=\"RSOrd" +
                "erItem_Receipt\" EntitySet=\"OrderItems\" /><End Role=\"RSReceipt_PaidItems\" EntityS" +
                "et=\"Receipts\" /></AssociationSet><AssociationSet Name=\"RSUser_AttendedOrders\" As" +
                "sociation=\"RestSys.Models.RSOrder_Attendees_RSUser_AttendedOrders\"><End Role=\"RS" +
                "Order_Attendees\" EntitySet=\"Orders\" /><End Role=\"RSUser_AttendedOrders\" EntitySe" +
                "t=\"Users\" /></AssociationSet><AssociationSet Name=\"RSReceipt_Order\" Association=" +
                "\"RestSys.Models.RSOrder_Receipts_RSReceipt_Order\"><End Role=\"RSOrder_Receipts\" E" +
                "ntitySet=\"Orders\" /><End Role=\"RSReceipt_Order\" EntitySet=\"Receipts\" /></Associa" +
                "tionSet><AssociationSet Name=\"RSReceipt_User\" Association=\"RestSys.Models.RSUser" +
                "_Receipts_RSReceipt_User\"><End Role=\"RSUser_Receipts\" EntitySet=\"Users\" /><End R" +
                "ole=\"RSReceipt_User\" EntitySet=\"Receipts\" /></AssociationSet><AssociationSet Nam" +
                "e=\"RSStockItem_Stock\" Association=\"RestSys.Models.RSStockItem_Stock_RSStock_Item" +
                "s\"><End Role=\"RSStockItem_Stock\" EntitySet=\"StockItems\" /><End Role=\"RSStock_Ite" +
                "ms\" EntitySet=\"Stocks\" /></AssociationSet></EntityContainer></Schema></edmx:Data" +
                "Services></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSNavigationItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Navigation")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSNavigationItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSNavigationItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isRoot">Initial value of IsRoot.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSNavigationItem CreateRSNavigationItem(int ID, bool isRoot)
        {
            RSNavigationItem rSNavigationItem = new RSNavigationItem();
            rSNavigationItem.Id = ID;
            rSNavigationItem.IsRoot = isRoot;
            return rSNavigationItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ChildrenOrder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChildrenOrder
        {
            get
            {
                return this._ChildrenOrder;
            }
            set
            {
                this.OnChildrenOrderChanging(value);
                this._ChildrenOrder = value;
                this.OnChildrenOrderChanged();
                this.OnPropertyChanged("ChildrenOrder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChildrenOrder;
        partial void OnChildrenOrderChanging(string value);
        partial void OnChildrenOrderChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
                this.OnPropertyChanged("Image");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Property IsRoot in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsRoot
        {
            get
            {
                return this._IsRoot;
            }
            set
            {
                this.OnIsRootChanging(value);
                this._IsRoot = value;
                this.OnIsRootChanged();
                this.OnPropertyChanged("IsRoot");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsRoot;
        partial void OnIsRootChanging(bool value);
        partial void OnIsRootChanged();
        /// <summary>
        /// There are no comments for Property Color in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this.OnColorChanging(value);
                this._Color = value;
                this.OnColorChanged();
                this.OnPropertyChanged("Color");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Color;
        partial void OnColorChanging(string value);
        partial void OnColorChanged();
        /// <summary>
        /// There are no comments for Children in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> Children
        {
            get
            {
                return this._Children;
            }
            set
            {
                this._Children = value;
                this.OnPropertyChanged("Children");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> _Children = new global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSNavigationItem Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this._Parent = value;
                this.OnPropertyChanged("Parent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSNavigationItem _Parent;
        /// <summary>
        /// There are no comments for ProductLink in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSProduct ProductLink
        {
            get
            {
                return this._ProductLink;
            }
            set
            {
                this._ProductLink = value;
                this.OnPropertyChanged("ProductLink");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSProduct _ProductLink;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSProduct in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Products")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSProduct : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSProduct object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="showOnMenu">Initial value of ShowOnMenu.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSProduct CreateRSProduct(int ID, double price, bool showOnMenu)
        {
            RSProduct rSProduct = new RSProduct();
            rSProduct.Id = ID;
            rSProduct.Price = price;
            rSProduct.ShowOnMenu = showOnMenu;
            return rSProduct;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Price;
        partial void OnPriceChanging(double value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property ShowOnMenu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool ShowOnMenu
        {
            get
            {
                return this._ShowOnMenu;
            }
            set
            {
                this.OnShowOnMenuChanging(value);
                this._ShowOnMenu = value;
                this.OnShowOnMenuChanged();
                this.OnPropertyChanged("ShowOnMenu");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ShowOnMenu;
        partial void OnShowOnMenuChanging(bool value);
        partial void OnShowOnMenuChanged();
        /// <summary>
        /// There are no comments for Property SerialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this.OnSerialNumberChanging(value);
                this._SerialNumber = value;
                this.OnSerialNumberChanged();
                this.OnPropertyChanged("SerialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerialNumber;
        partial void OnSerialNumberChanging(string value);
        partial void OnSerialNumberChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for DependentNavigationItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> DependentNavigationItems
        {
            get
            {
                return this._DependentNavigationItems;
            }
            set
            {
                this._DependentNavigationItems = value;
                this.OnPropertyChanged("DependentNavigationItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> _DependentNavigationItems = new global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for DependentOrderItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> DependentOrderItems
        {
            get
            {
                return this._DependentOrderItems;
            }
            set
            {
                this._DependentOrderItems = value;
                this.OnPropertyChanged("DependentOrderItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> _DependentOrderItems = new global::System.Data.Services.Client.DataServiceCollection<RSOrderItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSStockItem> Stocks
        {
            get
            {
                return this._Stocks;
            }
            set
            {
                this._Stocks = value;
                this.OnPropertyChanged("Stocks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSStockItem> _Stocks = new global::System.Data.Services.Client.DataServiceCollection<RSStockItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSOrderItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("OrderItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSOrderItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSOrderItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        /// <param name="state">Initial value of State.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSOrderItem CreateRSOrderItem(int ID, global::System.DateTime createdOn, int state)
        {
            RSOrderItem rSOrderItem = new RSOrderItem();
            rSOrderItem.Id = ID;
            rSOrderItem.CreatedOn = createdOn;
            rSOrderItem.State = state;
            return rSOrderItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _State;
        partial void OnStateChanging(int value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSOrder Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSOrder _Order;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSProduct Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSProduct _Product;
        /// <summary>
        /// There are no comments for Receipt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSReceipt Receipt
        {
            get
            {
                return this._Receipt;
            }
            set
            {
                this._Receipt = value;
                this.OnPropertyChanged("Receipt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSReceipt _Receipt;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSOrder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Orders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSOrder : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSOrder object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        /// <param name="active">Initial value of Active.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSOrder CreateRSOrder(int ID, global::System.DateTime createdOn, bool active)
        {
            RSOrder rSOrder = new RSOrder();
            rSOrder.Id = ID;
            rSOrder.CreatedOn = createdOn;
            rSOrder.Active = active;
            return rSOrder;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Attendees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSUser> Attendees
        {
            get
            {
                return this._Attendees;
            }
            set
            {
                this._Attendees = value;
                this.OnPropertyChanged("Attendees");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSUser> _Attendees = new global::System.Data.Services.Client.DataServiceCollection<RSUser>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> Items
        {
            get
            {
                return this._Items;
            }
            set
            {
                this._Items = value;
                this.OnPropertyChanged("Items");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> _Items = new global::System.Data.Services.Client.DataServiceCollection<RSOrderItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSReceipt> Receipts
        {
            get
            {
                return this._Receipts;
            }
            set
            {
                this._Receipts = value;
                this.OnPropertyChanged("Receipts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSReceipt> _Receipts = new global::System.Data.Services.Client.DataServiceCollection<RSReceipt>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSUser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSUser object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isAdmin">Initial value of IsAdmin.</param>
        /// <param name="isWaiter">Initial value of IsWaiter.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSUser CreateRSUser(int ID, bool isAdmin, bool isWaiter)
        {
            RSUser rSUser = new RSUser();
            rSUser.Id = ID;
            rSUser.IsAdmin = isAdmin;
            rSUser.IsWaiter = isWaiter;
            return rSUser;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this._Username = value;
                this.OnUsernameChanged();
                this.OnPropertyChanged("Username");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property PasswordHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] PasswordHash
        {
            get
            {
                if ((this._PasswordHash != null))
                {
                    return ((byte[])(this._PasswordHash.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this._PasswordHash = value;
                this.OnPasswordHashChanged();
                this.OnPropertyChanged("PasswordHash");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _PasswordHash;
        partial void OnPasswordHashChanging(byte[] value);
        partial void OnPasswordHashChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] PasswordSalt
        {
            get
            {
                if ((this._PasswordSalt != null))
                {
                    return ((byte[])(this._PasswordSalt.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this._PasswordSalt = value;
                this.OnPasswordSaltChanged();
                this.OnPropertyChanged("PasswordSalt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _PasswordSalt;
        partial void OnPasswordSaltChanging(byte[] value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property IsAdmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAdmin
        {
            get
            {
                return this._IsAdmin;
            }
            set
            {
                this.OnIsAdminChanging(value);
                this._IsAdmin = value;
                this.OnIsAdminChanged();
                this.OnPropertyChanged("IsAdmin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAdmin;
        partial void OnIsAdminChanging(bool value);
        partial void OnIsAdminChanged();
        /// <summary>
        /// There are no comments for Property IsWaiter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsWaiter
        {
            get
            {
                return this._IsWaiter;
            }
            set
            {
                this.OnIsWaiterChanging(value);
                this._IsWaiter = value;
                this.OnIsWaiterChanged();
                this.OnPropertyChanged("IsWaiter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsWaiter;
        partial void OnIsWaiterChanging(bool value);
        partial void OnIsWaiterChanged();
        /// <summary>
        /// There are no comments for AttendedOrders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrder> AttendedOrders
        {
            get
            {
                return this._AttendedOrders;
            }
            set
            {
                this._AttendedOrders = value;
                this.OnPropertyChanged("AttendedOrders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrder> _AttendedOrders = new global::System.Data.Services.Client.DataServiceCollection<RSOrder>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSReceipt> Receipts
        {
            get
            {
                return this._Receipts;
            }
            set
            {
                this._Receipts = value;
                this.OnPropertyChanged("Receipts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSReceipt> _Receipts = new global::System.Data.Services.Client.DataServiceCollection<RSReceipt>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSReceipt in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Receipts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSReceipt : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSReceipt object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSReceipt CreateRSReceipt(int ID, global::System.DateTime createdOn)
        {
            RSReceipt rSReceipt = new RSReceipt();
            rSReceipt.Id = ID;
            rSReceipt.CreatedOn = createdOn;
            return rSReceipt;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSOrder Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSOrder _Order;
        /// <summary>
        /// There are no comments for PaidItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> PaidItems
        {
            get
            {
                return this._PaidItems;
            }
            set
            {
                this._PaidItems = value;
                this.OnPropertyChanged("PaidItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> _PaidItems = new global::System.Data.Services.Client.DataServiceCollection<RSOrderItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSUser User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSUser _User;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSStockItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("StockItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSStockItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSStockItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="amount">Initial value of Amount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSStockItem CreateRSStockItem(int ID, double amount)
        {
            RSStockItem rSStockItem = new RSStockItem();
            rSStockItem.Id = ID;
            rSStockItem.Amount = amount;
            return rSStockItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
                this.OnPropertyChanged("Amount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Amount;
        partial void OnAmountChanging(double value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSProduct Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSProduct _Product;
        /// <summary>
        /// There are no comments for Stock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSStock Stock
        {
            get
            {
                return this._Stock;
            }
            set
            {
                this._Stock = value;
                this.OnPropertyChanged("Stock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSStock _Stock;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSStock in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Stocks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSStock : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSStock object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSStock CreateRSStock(int ID)
        {
            RSStock rSStock = new RSStock();
            rSStock.Id = ID;
            return rSStock;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Unit
        {
            get
            {
                return this._Unit;
            }
            set
            {
                this.OnUnitChanging(value);
                this._Unit = value;
                this.OnUnitChanged();
                this.OnPropertyChanged("Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Unit;
        partial void OnUnitChanging(string value);
        partial void OnUnitChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property SerialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this.OnSerialNumberChanging(value);
                this._SerialNumber = value;
                this.OnSerialNumberChanged();
                this.OnPropertyChanged("SerialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerialNumber;
        partial void OnSerialNumberChanging(string value);
        partial void OnSerialNumberChanged();
        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSStockItem> Items
        {
            get
            {
                return this._Items;
            }
            set
            {
                this._Items = value;
                this.OnPropertyChanged("Items");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSStockItem> _Items = new global::System.Data.Services.Client.DataServiceCollection<RSStockItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSStyle in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Styles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSStyle : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSStyle object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="selected">Initial value of Selected.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSStyle CreateRSStyle(int ID, int type, bool selected)
        {
            RSStyle rSStyle = new RSStyle();
            rSStyle.Id = ID;
            rSStyle.Type = type;
            rSStyle.Selected = selected;
            return rSStyle;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this._Path = value;
                this.OnPathChanged();
                this.OnPropertyChanged("Path");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Selected in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Selected
        {
            get
            {
                return this._Selected;
            }
            set
            {
                this.OnSelectedChanging(value);
                this._Selected = value;
                this.OnSelectedChanged();
                this.OnPropertyChanged("Selected");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Selected;
        partial void OnSelectedChanging(bool value);
        partial void OnSelectedChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
