//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7. 4. 2014 23:40:45
namespace RestSys.Client.Services.EntityService
{
    
    /// <summary>
    /// There are no comments for RSDbContext in the schema.
    /// </summary>
    public partial class RSDbContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new RSDbContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSDbContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "RestSys.Models", "RestSys.Client.Services.EntityService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("RestSys.Client.Services.EntityService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("RestSys.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Navigation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSNavigationItem> Navigation
        {
            get
            {
                if ((this._Navigation == null))
                {
                    this._Navigation = base.CreateQuery<RSNavigationItem>("Navigation");
                }
                return this._Navigation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSNavigationItem> _Navigation;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSProduct> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<RSProduct>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSProduct> _Products;
        /// <summary>
        /// There are no comments for RSOrderItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSOrderItem> RSOrderItems
        {
            get
            {
                if ((this._RSOrderItems == null))
                {
                    this._RSOrderItems = base.CreateQuery<RSOrderItem>("RSOrderItems");
                }
                return this._RSOrderItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSOrderItem> _RSOrderItems;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSOrder> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<RSOrder>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSOrder> _Orders;
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSReceipt> Receipts
        {
            get
            {
                if ((this._Receipts == null))
                {
                    this._Receipts = base.CreateQuery<RSReceipt>("Receipts");
                }
                return this._Receipts;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSReceipt> _Receipts;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSUser> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<RSUser>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSUser> _Users;
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSStock> Stocks
        {
            get
            {
                if ((this._Stocks == null))
                {
                    this._Stocks = base.CreateQuery<RSStock>("Stocks");
                }
                return this._Stocks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSStock> _Stocks;
        /// <summary>
        /// There are no comments for Styles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RSStyle> Styles
        {
            get
            {
                if ((this._Styles == null))
                {
                    this._Styles = base.CreateQuery<RSStyle>("Styles");
                }
                return this._Styles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RSStyle> _Styles;
        /// <summary>
        /// There are no comments for Navigation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNavigation(RSNavigationItem rSNavigationItem)
        {
            base.AddObject("Navigation", rSNavigationItem);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProducts(RSProduct rSProduct)
        {
            base.AddObject("Products", rSProduct);
        }
        /// <summary>
        /// There are no comments for RSOrderItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRSOrderItems(RSOrderItem rSOrderItem)
        {
            base.AddObject("RSOrderItems", rSOrderItem);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOrders(RSOrder rSOrder)
        {
            base.AddObject("Orders", rSOrder);
        }
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToReceipts(RSReceipt rSReceipt)
        {
            base.AddObject("Receipts", rSReceipt);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(RSUser rSUser)
        {
            base.AddObject("Users", rSUser);
        }
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStocks(RSStock rSStock)
        {
            base.AddObject("Stocks", rSStock);
        }
        /// <summary>
        /// There are no comments for Styles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStyles(RSStyle rSStyle)
        {
            base.AddObject("Styles", rSStyle);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"RestSys.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\">" +
                "<EntityType Name=\"RSNavigationItem\"><Key><PropertyRef Name=\"Id\" /></Key><Propert" +
                "y Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Position\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Proper" +
                "ty Name=\"Description\" Type=\"Edm.String\" /><Property Name=\"Image\" Type=\"Edm.Strin" +
                "g\" /><NavigationProperty Name=\"Children\" Relationship=\"RestSys.Models.RSNavigati" +
                "onItem_Children_RSNavigationItem_Parent\" ToRole=\"RSNavigationItem_Parent\" FromRo" +
                "le=\"RSNavigationItem_Children\" /><NavigationProperty Name=\"Parent\" Relationship=" +
                "\"RestSys.Models.RSNavigationItem_Children_RSNavigationItem_Parent\" ToRole=\"RSNav" +
                "igationItem_Children\" FromRole=\"RSNavigationItem_Parent\" /><NavigationProperty N" +
                "ame=\"ProductLink\" Relationship=\"RestSys.Models.RSNavigationItem_ProductLink_RSPr" +
                "oduct_DependentNavigationItems\" ToRole=\"RSProduct_DependentNavigationItems\" From" +
                "Role=\"RSNavigationItem_ProductLink\" /></EntityType><EntityType Name=\"RSProduct\">" +
                "<Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullabl" +
                "e=\"false\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Property Name=\"Descripti" +
                "on\" Type=\"Edm.String\" /><Property Name=\"Price\" Type=\"Edm.Double\" Nullable=\"false" +
                "\" /><Property Name=\"ShowOnMenu\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property " +
                "Name=\"SerialNumber\" Type=\"Edm.String\" /><Property Name=\"Amount\" Type=\"Edm.Double" +
                "\" Nullable=\"false\" /><Property Name=\"Category\" Type=\"Edm.String\" /><NavigationPr" +
                "operty Name=\"DependentNavigationItems\" Relationship=\"RestSys.Models.RSNavigation" +
                "Item_ProductLink_RSProduct_DependentNavigationItems\" ToRole=\"RSNavigationItem_Pr" +
                "oductLink\" FromRole=\"RSProduct_DependentNavigationItems\" /><NavigationProperty N" +
                "ame=\"DependentOrderItems\" Relationship=\"RestSys.Models.RSProduct_DependentOrderI" +
                "tems_RSOrderItem_Product\" ToRole=\"RSOrderItem_Product\" FromRole=\"RSProduct_Depen" +
                "dentOrderItems\" /><NavigationProperty Name=\"Stocks\" Relationship=\"RestSys.Models" +
                ".RSProduct_Stocks_RSStock_DependentProducts\" ToRole=\"RSStock_DependentProducts\" " +
                "FromRole=\"RSProduct_Stocks\" /></EntityType><EntityType Name=\"RSOrderItem\"><Key><" +
                "PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fal" +
                "se\" /><Property Name=\"Quantity\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationP" +
                "roperty Name=\"Order\" Relationship=\"RestSys.Models.RSOrderItem_Order_RSOrder_Item" +
                "s\" ToRole=\"RSOrder_Items\" FromRole=\"RSOrderItem_Order\" /><NavigationProperty Nam" +
                "e=\"Product\" Relationship=\"RestSys.Models.RSProduct_DependentOrderItems_RSOrderIt" +
                "em_Product\" ToRole=\"RSProduct_DependentOrderItems\" FromRole=\"RSOrderItem_Product" +
                "\" /><NavigationProperty Name=\"Receipt\" Relationship=\"RestSys.Models.RSOrderItem_" +
                "Receipt_RSReceipt_PaidItems\" ToRole=\"RSReceipt_PaidItems\" FromRole=\"RSOrderItem_" +
                "Receipt\" /></EntityType><EntityType Name=\"RSOrder\"><Key><PropertyRef Name=\"Id\" /" +
                "></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"O" +
                "rderedOn\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Notes\" Type=\"Ed" +
                "m.String\" /><NavigationProperty Name=\"Items\" Relationship=\"RestSys.Models.RSOrde" +
                "rItem_Order_RSOrder_Items\" ToRole=\"RSOrderItem_Order\" FromRole=\"RSOrder_Items\" /" +
                "><NavigationProperty Name=\"Receipts\" Relationship=\"RestSys.Models.RSOrder_Receip" +
                "ts_RSReceipt_Order\" ToRole=\"RSReceipt_Order\" FromRole=\"RSOrder_Receipts\" /></Ent" +
                "ityType><EntityType Name=\"RSReceipt\"><Key><PropertyRef Name=\"Id\" /></Key><Proper" +
                "ty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CreatedOn\" Type" +
                "=\"Edm.DateTime\" Nullable=\"false\" /><NavigationProperty Name=\"Order\" Relationship" +
                "=\"RestSys.Models.RSOrder_Receipts_RSReceipt_Order\" ToRole=\"RSOrder_Receipts\" Fro" +
                "mRole=\"RSReceipt_Order\" /><NavigationProperty Name=\"PaidItems\" Relationship=\"Res" +
                "tSys.Models.RSOrderItem_Receipt_RSReceipt_PaidItems\" ToRole=\"RSOrderItem_Receipt" +
                "\" FromRole=\"RSReceipt_PaidItems\" /><NavigationProperty Name=\"User\" Relationship=" +
                "\"RestSys.Models.RSReceipt_User_RSUser_Receipts\" ToRole=\"RSUser_Receipts\" FromRol" +
                "e=\"RSReceipt_User\" /></EntityType><EntityType Name=\"RSUser\"><Key><PropertyRef Na" +
                "me=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Username\" Type=\"Edm.String\" />" +
                "<Property Name=\"PasswordHash\" Type=\"Edm.Binary\" /><Property Name=\"PasswordSalt\" " +
                "Type=\"Edm.Binary\" /><Property Name=\"IsAdmin\" Type=\"Edm.Boolean\" Nullable=\"false\"" +
                " /><Property Name=\"IsWaiter\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Nam" +
                "e=\"IsDiscountManager\" Type=\"Edm.Boolean\" Nullable=\"false\" /><NavigationProperty " +
                "Name=\"Receipts\" Relationship=\"RestSys.Models.RSReceipt_User_RSUser_Receipts\" ToR" +
                "ole=\"RSReceipt_User\" FromRole=\"RSUser_Receipts\" /></EntityType><EntityType Name=" +
                "\"RSStock\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int3" +
                "2\" Nullable=\"false\" /><Property Name=\"Title\" Type=\"Edm.String\" /><Property Name=" +
                "\"Quantity\" Type=\"Edm.Double\" Nullable=\"false\" /><Property Name=\"Notes\" Type=\"Edm" +
                ".String\" /><Property Name=\"SerialNumber\" Type=\"Edm.String\" /><NavigationProperty" +
                " Name=\"DependentProducts\" Relationship=\"RestSys.Models.RSProduct_Stocks_RSStock_" +
                "DependentProducts\" ToRole=\"RSProduct_Stocks\" FromRole=\"RSStock_DependentProducts" +
                "\" /></EntityType><EntityType Name=\"RSStyle\"><Key><PropertyRef Name=\"Id\" /></Key>" +
                "<Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Code\" Ty" +
                "pe=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Path\" Type=\"Edm.String\" /><Pro" +
                "perty Name=\"Type\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Title\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"Notes\" Type=\"Edm.String\" /><Property Name=\"Sele" +
                "cted\" Type=\"Edm.Boolean\" Nullable=\"false\" /></EntityType><Association Name=\"RSNa" +
                "vigationItem_Children_RSNavigationItem_Parent\"><End Type=\"RestSys.Models.RSNavig" +
                "ationItem\" Role=\"RSNavigationItem_Parent\" Multiplicity=\"*\" /><End Type=\"RestSys." +
                "Models.RSNavigationItem\" Role=\"RSNavigationItem_Children\" Multiplicity=\"0..1\" />" +
                "</Association><Association Name=\"RSNavigationItem_ProductLink_RSProduct_Dependen" +
                "tNavigationItems\"><End Type=\"RestSys.Models.RSProduct\" Role=\"RSProduct_Dependent" +
                "NavigationItems\" Multiplicity=\"0..1\" /><End Type=\"RestSys.Models.RSNavigationIte" +
                "m\" Role=\"RSNavigationItem_ProductLink\" Multiplicity=\"*\" /></Association><Associa" +
                "tion Name=\"RSProduct_DependentOrderItems_RSOrderItem_Product\"><End Type=\"RestSys" +
                ".Models.RSOrderItem\" Role=\"RSOrderItem_Product\" Multiplicity=\"*\" /><End Type=\"Re" +
                "stSys.Models.RSProduct\" Role=\"RSProduct_DependentOrderItems\" Multiplicity=\"0..1\"" +
                " /></Association><Association Name=\"RSProduct_Stocks_RSStock_DependentProducts\">" +
                "<End Type=\"RestSys.Models.RSStock\" Role=\"RSStock_DependentProducts\" Multiplicity" +
                "=\"*\" /><End Type=\"RestSys.Models.RSProduct\" Role=\"RSProduct_Stocks\" Multiplicity" +
                "=\"*\" /></Association><Association Name=\"RSOrderItem_Order_RSOrder_Items\"><End Ty" +
                "pe=\"RestSys.Models.RSOrder\" Role=\"RSOrder_Items\" Multiplicity=\"0..1\" /><End Type" +
                "=\"RestSys.Models.RSOrderItem\" Role=\"RSOrderItem_Order\" Multiplicity=\"*\" /></Asso" +
                "ciation><Association Name=\"RSOrderItem_Receipt_RSReceipt_PaidItems\"><End Type=\"R" +
                "estSys.Models.RSReceipt\" Role=\"RSReceipt_PaidItems\" Multiplicity=\"0..1\" /><End T" +
                "ype=\"RestSys.Models.RSOrderItem\" Role=\"RSOrderItem_Receipt\" Multiplicity=\"*\" /><" +
                "/Association><Association Name=\"RSOrder_Receipts_RSReceipt_";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "Order\"><End Type=\"RestSys.Models.RSReceipt\" Role=\"RSReceipt_Order\" Multiplicity=\"" +
                "*\" /><End Type=\"RestSys.Models.RSOrder\" Role=\"RSOrder_Receipts\" Multiplicity=\"0." +
                ".1\" /></Association><Association Name=\"RSReceipt_User_RSUser_Receipts\"><End Type" +
                "=\"RestSys.Models.RSUser\" Role=\"RSUser_Receipts\" Multiplicity=\"0..1\" /><End Type=" +
                "\"RestSys.Models.RSReceipt\" Role=\"RSReceipt_User\" Multiplicity=\"*\" /></Associatio" +
                "n><EntityContainer Name=\"RSDbContext\" m:IsDefaultEntityContainer=\"true\"><EntityS" +
                "et Name=\"Navigation\" EntityType=\"RestSys.Models.RSNavigationItem\" /><EntitySet N" +
                "ame=\"Products\" EntityType=\"RestSys.Models.RSProduct\" /><EntitySet Name=\"RSOrderI" +
                "tems\" EntityType=\"RestSys.Models.RSOrderItem\" /><EntitySet Name=\"Orders\" EntityT" +
                "ype=\"RestSys.Models.RSOrder\" /><EntitySet Name=\"Receipts\" EntityType=\"RestSys.Mo" +
                "dels.RSReceipt\" /><EntitySet Name=\"Users\" EntityType=\"RestSys.Models.RSUser\" /><" +
                "EntitySet Name=\"Stocks\" EntityType=\"RestSys.Models.RSStock\" /><EntitySet Name=\"S" +
                "tyles\" EntityType=\"RestSys.Models.RSStyle\" /><AssociationSet Name=\"RSNavigationI" +
                "tem_Children\" Association=\"RestSys.Models.RSNavigationItem_Children_RSNavigation" +
                "Item_Parent\"><End Role=\"RSNavigationItem_Children\" EntitySet=\"Navigation\" /><End" +
                " Role=\"RSNavigationItem_Parent\" EntitySet=\"Navigation\" /></AssociationSet><Assoc" +
                "iationSet Name=\"RSProduct_DependentNavigationItems\" Association=\"RestSys.Models." +
                "RSNavigationItem_ProductLink_RSProduct_DependentNavigationItems\"><End Role=\"RSNa" +
                "vigationItem_ProductLink\" EntitySet=\"Navigation\" /><End Role=\"RSProduct_Dependen" +
                "tNavigationItems\" EntitySet=\"Products\" /></AssociationSet><AssociationSet Name=\"" +
                "RSOrderItem_Product\" Association=\"RestSys.Models.RSProduct_DependentOrderItems_R" +
                "SOrderItem_Product\"><End Role=\"RSProduct_DependentOrderItems\" EntitySet=\"Product" +
                "s\" /><End Role=\"RSOrderItem_Product\" EntitySet=\"RSOrderItems\" /></AssociationSet" +
                "><AssociationSet Name=\"RSStock_DependentProducts\" Association=\"RestSys.Models.RS" +
                "Product_Stocks_RSStock_DependentProducts\"><End Role=\"RSProduct_Stocks\" EntitySet" +
                "=\"Products\" /><End Role=\"RSStock_DependentProducts\" EntitySet=\"Stocks\" /></Assoc" +
                "iationSet><AssociationSet Name=\"RSOrder_Items\" Association=\"RestSys.Models.RSOrd" +
                "erItem_Order_RSOrder_Items\"><End Role=\"RSOrderItem_Order\" EntitySet=\"RSOrderItem" +
                "s\" /><End Role=\"RSOrder_Items\" EntitySet=\"Orders\" /></AssociationSet><Associatio" +
                "nSet Name=\"RSReceipt_PaidItems\" Association=\"RestSys.Models.RSOrderItem_Receipt_" +
                "RSReceipt_PaidItems\"><End Role=\"RSOrderItem_Receipt\" EntitySet=\"RSOrderItems\" />" +
                "<End Role=\"RSReceipt_PaidItems\" EntitySet=\"Receipts\" /></AssociationSet><Associa" +
                "tionSet Name=\"RSReceipt_Order\" Association=\"RestSys.Models.RSOrder_Receipts_RSRe" +
                "ceipt_Order\"><End Role=\"RSOrder_Receipts\" EntitySet=\"Orders\" /><End Role=\"RSRece" +
                "ipt_Order\" EntitySet=\"Receipts\" /></AssociationSet><AssociationSet Name=\"RSRecei" +
                "pt_User\" Association=\"RestSys.Models.RSReceipt_User_RSUser_Receipts\"><End Role=\"" +
                "RSReceipt_User\" EntitySet=\"Receipts\" /><End Role=\"RSUser_Receipts\" EntitySet=\"Us" +
                "ers\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Ed" +
                "mx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSNavigationItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Navigation")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSNavigationItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSNavigationItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="position">Initial value of Position.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSNavigationItem CreateRSNavigationItem(int ID, int position)
        {
            RSNavigationItem rSNavigationItem = new RSNavigationItem();
            rSNavigationItem.Id = ID;
            rSNavigationItem.Position = position;
            return rSNavigationItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this.OnPositionChanging(value);
                this._Position = value;
                this.OnPositionChanged();
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Position;
        partial void OnPositionChanging(int value);
        partial void OnPositionChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Image in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Image
        {
            get
            {
                return this._Image;
            }
            set
            {
                this.OnImageChanging(value);
                this._Image = value;
                this.OnImageChanged();
                this.OnPropertyChanged("Image");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Image;
        partial void OnImageChanging(string value);
        partial void OnImageChanged();
        /// <summary>
        /// There are no comments for Children in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> Children
        {
            get
            {
                return this._Children;
            }
            set
            {
                this._Children = value;
                this.OnPropertyChanged("Children");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> _Children = new global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSNavigationItem Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this._Parent = value;
                this.OnPropertyChanged("Parent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSNavigationItem _Parent;
        /// <summary>
        /// There are no comments for ProductLink in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSProduct ProductLink
        {
            get
            {
                return this._ProductLink;
            }
            set
            {
                this._ProductLink = value;
                this.OnPropertyChanged("ProductLink");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSProduct _ProductLink;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSProduct in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Products")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSProduct : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSProduct object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="showOnMenu">Initial value of ShowOnMenu.</param>
        /// <param name="amount">Initial value of Amount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSProduct CreateRSProduct(int ID, double price, bool showOnMenu, double amount)
        {
            RSProduct rSProduct = new RSProduct();
            rSProduct.Id = ID;
            rSProduct.Price = price;
            rSProduct.ShowOnMenu = showOnMenu;
            rSProduct.Amount = amount;
            return rSProduct;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Price;
        partial void OnPriceChanging(double value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property ShowOnMenu in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool ShowOnMenu
        {
            get
            {
                return this._ShowOnMenu;
            }
            set
            {
                this.OnShowOnMenuChanging(value);
                this._ShowOnMenu = value;
                this.OnShowOnMenuChanged();
                this.OnPropertyChanged("ShowOnMenu");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ShowOnMenu;
        partial void OnShowOnMenuChanging(bool value);
        partial void OnShowOnMenuChanged();
        /// <summary>
        /// There are no comments for Property SerialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this.OnSerialNumberChanging(value);
                this._SerialNumber = value;
                this.OnSerialNumberChanged();
                this.OnPropertyChanged("SerialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerialNumber;
        partial void OnSerialNumberChanging(string value);
        partial void OnSerialNumberChanged();
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
                this.OnPropertyChanged("Amount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Amount;
        partial void OnAmountChanging(double value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for DependentNavigationItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> DependentNavigationItems
        {
            get
            {
                return this._DependentNavigationItems;
            }
            set
            {
                this._DependentNavigationItems = value;
                this.OnPropertyChanged("DependentNavigationItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem> _DependentNavigationItems = new global::System.Data.Services.Client.DataServiceCollection<RSNavigationItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for DependentOrderItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> DependentOrderItems
        {
            get
            {
                return this._DependentOrderItems;
            }
            set
            {
                this._DependentOrderItems = value;
                this.OnPropertyChanged("DependentOrderItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> _DependentOrderItems = new global::System.Data.Services.Client.DataServiceCollection<RSOrderItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Stocks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSStock> Stocks
        {
            get
            {
                return this._Stocks;
            }
            set
            {
                this._Stocks = value;
                this.OnPropertyChanged("Stocks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSStock> _Stocks = new global::System.Data.Services.Client.DataServiceCollection<RSStock>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSOrderItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RSOrderItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSOrderItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSOrderItem object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSOrderItem CreateRSOrderItem(int ID, int quantity)
        {
            RSOrderItem rSOrderItem = new RSOrderItem();
            rSOrderItem.Id = ID;
            rSOrderItem.Quantity = quantity;
            return rSOrderItem;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSOrder Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSOrder _Order;
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSProduct Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
                this.OnPropertyChanged("Product");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSProduct _Product;
        /// <summary>
        /// There are no comments for Receipt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSReceipt Receipt
        {
            get
            {
                return this._Receipt;
            }
            set
            {
                this._Receipt = value;
                this.OnPropertyChanged("Receipt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSReceipt _Receipt;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSOrder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Orders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSOrder : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSOrder object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="orderedOn">Initial value of OrderedOn.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSOrder CreateRSOrder(int ID, global::System.DateTime orderedOn)
        {
            RSOrder rSOrder = new RSOrder();
            rSOrder.Id = ID;
            rSOrder.OrderedOn = orderedOn;
            return rSOrder;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property OrderedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime OrderedOn
        {
            get
            {
                return this._OrderedOn;
            }
            set
            {
                this.OnOrderedOnChanging(value);
                this._OrderedOn = value;
                this.OnOrderedOnChanged();
                this.OnPropertyChanged("OrderedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _OrderedOn;
        partial void OnOrderedOnChanging(global::System.DateTime value);
        partial void OnOrderedOnChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Items in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> Items
        {
            get
            {
                return this._Items;
            }
            set
            {
                this._Items = value;
                this.OnPropertyChanged("Items");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> _Items = new global::System.Data.Services.Client.DataServiceCollection<RSOrderItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSReceipt> Receipts
        {
            get
            {
                return this._Receipts;
            }
            set
            {
                this._Receipts = value;
                this.OnPropertyChanged("Receipts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSReceipt> _Receipts = new global::System.Data.Services.Client.DataServiceCollection<RSReceipt>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSReceipt in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Receipts")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSReceipt : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSReceipt object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSReceipt CreateRSReceipt(int ID, global::System.DateTime createdOn)
        {
            RSReceipt rSReceipt = new RSReceipt();
            rSReceipt.Id = ID;
            rSReceipt.CreatedOn = createdOn;
            return rSReceipt;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this._CreatedOn = value;
                this.OnCreatedOnChanged();
                this.OnPropertyChanged("CreatedOn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Order in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSOrder Order
        {
            get
            {
                return this._Order;
            }
            set
            {
                this._Order = value;
                this.OnPropertyChanged("Order");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSOrder _Order;
        /// <summary>
        /// There are no comments for PaidItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> PaidItems
        {
            get
            {
                return this._PaidItems;
            }
            set
            {
                this._PaidItems = value;
                this.OnPropertyChanged("PaidItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSOrderItem> _PaidItems = new global::System.Data.Services.Client.DataServiceCollection<RSOrderItem>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RSUser User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RSUser _User;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSUser in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSUser : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSUser object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isAdmin">Initial value of IsAdmin.</param>
        /// <param name="isWaiter">Initial value of IsWaiter.</param>
        /// <param name="isDiscountManager">Initial value of IsDiscountManager.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSUser CreateRSUser(int ID, bool isAdmin, bool isWaiter, bool isDiscountManager)
        {
            RSUser rSUser = new RSUser();
            rSUser.Id = ID;
            rSUser.IsAdmin = isAdmin;
            rSUser.IsWaiter = isWaiter;
            rSUser.IsDiscountManager = isDiscountManager;
            return rSUser;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this._Username = value;
                this.OnUsernameChanged();
                this.OnPropertyChanged("Username");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property PasswordHash in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] PasswordHash
        {
            get
            {
                if ((this._PasswordHash != null))
                {
                    return ((byte[])(this._PasswordHash.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPasswordHashChanging(value);
                this._PasswordHash = value;
                this.OnPasswordHashChanged();
                this.OnPropertyChanged("PasswordHash");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _PasswordHash;
        partial void OnPasswordHashChanging(byte[] value);
        partial void OnPasswordHashChanged();
        /// <summary>
        /// There are no comments for Property PasswordSalt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] PasswordSalt
        {
            get
            {
                if ((this._PasswordSalt != null))
                {
                    return ((byte[])(this._PasswordSalt.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnPasswordSaltChanging(value);
                this._PasswordSalt = value;
                this.OnPasswordSaltChanged();
                this.OnPropertyChanged("PasswordSalt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _PasswordSalt;
        partial void OnPasswordSaltChanging(byte[] value);
        partial void OnPasswordSaltChanged();
        /// <summary>
        /// There are no comments for Property IsAdmin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAdmin
        {
            get
            {
                return this._IsAdmin;
            }
            set
            {
                this.OnIsAdminChanging(value);
                this._IsAdmin = value;
                this.OnIsAdminChanged();
                this.OnPropertyChanged("IsAdmin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAdmin;
        partial void OnIsAdminChanging(bool value);
        partial void OnIsAdminChanged();
        /// <summary>
        /// There are no comments for Property IsWaiter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsWaiter
        {
            get
            {
                return this._IsWaiter;
            }
            set
            {
                this.OnIsWaiterChanging(value);
                this._IsWaiter = value;
                this.OnIsWaiterChanged();
                this.OnPropertyChanged("IsWaiter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsWaiter;
        partial void OnIsWaiterChanging(bool value);
        partial void OnIsWaiterChanged();
        /// <summary>
        /// There are no comments for Property IsDiscountManager in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsDiscountManager
        {
            get
            {
                return this._IsDiscountManager;
            }
            set
            {
                this.OnIsDiscountManagerChanging(value);
                this._IsDiscountManager = value;
                this.OnIsDiscountManagerChanged();
                this.OnPropertyChanged("IsDiscountManager");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsDiscountManager;
        partial void OnIsDiscountManagerChanging(bool value);
        partial void OnIsDiscountManagerChanged();
        /// <summary>
        /// There are no comments for Receipts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSReceipt> Receipts
        {
            get
            {
                return this._Receipts;
            }
            set
            {
                this._Receipts = value;
                this.OnPropertyChanged("Receipts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSReceipt> _Receipts = new global::System.Data.Services.Client.DataServiceCollection<RSReceipt>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSStock in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Stocks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSStock : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSStock object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSStock CreateRSStock(int ID, double quantity)
        {
            RSStock rSStock = new RSStock();
            rSStock.Id = ID;
            rSStock.Quantity = quantity;
            return rSStock;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Quantity;
        partial void OnQuantityChanging(double value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property SerialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this.OnSerialNumberChanging(value);
                this._SerialNumber = value;
                this.OnSerialNumberChanged();
                this.OnPropertyChanged("SerialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerialNumber;
        partial void OnSerialNumberChanging(string value);
        partial void OnSerialNumberChanged();
        /// <summary>
        /// There are no comments for DependentProducts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RSProduct> DependentProducts
        {
            get
            {
                return this._DependentProducts;
            }
            set
            {
                this._DependentProducts = value;
                this.OnPropertyChanged("DependentProducts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RSProduct> _DependentProducts = new global::System.Data.Services.Client.DataServiceCollection<RSProduct>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RestSys.Models.RSStyle in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Styles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class RSStyle : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RSStyle object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="selected">Initial value of Selected.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RSStyle CreateRSStyle(int ID, int code, int type, bool selected)
        {
            RSStyle rSStyle = new RSStyle();
            rSStyle.Id = ID;
            rSStyle.Code = code;
            rSStyle.Type = type;
            rSStyle.Selected = selected;
            return rSStyle;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Code;
        partial void OnCodeChanging(int value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this._Path = value;
                this.OnPathChanged();
                this.OnPropertyChanged("Path");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Type;
        partial void OnTypeChanging(int value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property Selected in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Selected
        {
            get
            {
                return this._Selected;
            }
            set
            {
                this.OnSelectedChanging(value);
                this._Selected = value;
                this.OnSelectedChanged();
                this.OnPropertyChanged("Selected");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Selected;
        partial void OnSelectedChanging(bool value);
        partial void OnSelectedChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
