//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSys.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSys.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit uživatele.
        /// </summary>
        public static string AccountCreate {
            get {
                return ResourceManager.GetString("AccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat uživatele.
        /// </summary>
        public static string AccountDelete {
            get {
                return ResourceManager.GetString("AccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o uživateli.
        /// </summary>
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit uživatele.
        /// </summary>
        public static string AccountEdit {
            get {
                return ResourceManager.GetString("AccountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled uživatelů.
        /// </summary>
        public static string AccountIndex {
            get {
                return ResourceManager.GetString("AccountIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat tuto položku?.
        /// </summary>
        public static string AreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na seznam.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ověření hesla.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení selhalo.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jste již přihlášeni.
        /// </summary>
        public static string LoginRedundant {
            get {
                return ResourceManager.GetString("LoginRedundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigace.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit položku navigace.
        /// </summary>
        public static string NavigationCreate {
            get {
                return ResourceManager.GetString("NavigationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazatpoložku navigace.
        /// </summary>
        public static string NavigationDelete {
            get {
                return ResourceManager.GetString("NavigationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o položce navigace.
        /// </summary>
        public static string NavigationDetails {
            get {
                return ResourceManager.GetString("NavigationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit položku navigace.
        /// </summary>
        public static string NavigationEdit {
            get {
                return ResourceManager.GetString("NavigationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled navigace v klientské aplikaci.
        /// </summary>
        public static string NavigationIndex {
            get {
                return ResourceManager.GetString("NavigationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávka.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit objednávku.
        /// </summary>
        public static string OrderCreate {
            get {
                return ResourceManager.GetString("OrderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat objednávku.
        /// </summary>
        public static string OrderDelete {
            get {
                return ResourceManager.GetString("OrderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o objednávce.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit objednávku.
        /// </summary>
        public static string OrderEdit {
            get {
                return ResourceManager.GetString("OrderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled objednávek.
        /// </summary>
        public static string OrderIndex {
            get {
                return ResourceManager.GetString("OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objednávky.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla se liší.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit produkt.
        /// </summary>
        public static string ProductCreate {
            get {
                return ResourceManager.GetString("ProductCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat produkt.
        /// </summary>
        public static string ProductDelete {
            get {
                return ResourceManager.GetString("ProductDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o produktu.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit produkt.
        /// </summary>
        public static string ProductEdit {
            get {
                return ResourceManager.GetString("ProductEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled produktů.
        /// </summary>
        public static string ProductIndex {
            get {
                return ResourceManager.GetString("ProductIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení do systému.
        /// </summary>
        public static string RestSysLogin {
            get {
                return ResourceManager.GetString("RestSysLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka skladu.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit zboží.
        /// </summary>
        public static string StockCreate {
            get {
                return ResourceManager.GetString("StockCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat zboží.
        /// </summary>
        public static string StockDelete {
            get {
                return ResourceManager.GetString("StockDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podrobnosti o zboží.
        /// </summary>
        public static string StockDetails {
            get {
                return ResourceManager.GetString("StockDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit zboží.
        /// </summary>
        public static string StockEdit {
            get {
                return ResourceManager.GetString("StockEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad.
        /// </summary>
        public static string StockIndex {
            get {
                return ResourceManager.GetString("StockIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklad.
        /// </summary>
        public static string Stocks {
            get {
                return ResourceManager.GetString("Stocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková cena.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelské jméno.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelé.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
