// <auto-generated />
namespace RestSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class stylebadcodetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stylebadcodetype));
        
        string IMigrationMetadata.Id
        {
            get { return "201404072210358_style-bad-code-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
