// <auto-generated />
namespace RestSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class quantityisstockitems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quantityisstockitems));
        
        string IMigrationMetadata.Id
        {
            get { return "201405041504395_quantityisstockitems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
