// <auto-generated />
namespace RestSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class navigation_root : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(navigation_root));
        
        string IMigrationMetadata.Id
        {
            get { return "201404131849588_navigation_root"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
